### ISSUE TITLE
We need a basic React APP with Tailwind CSS

### ISSUE THREAD

**Issue by nimit2801** [HackClubNUV/Spilled-My-Coffee-Here-UI#1]
1. Basic React App (Hooks/Component based)
2. Use TailWind CSS library

> Please use this issue with reference to the PR.

**Comment by shreyanshi16** [comment]
Issue was solved with f4832737aae9c7a8b6da65b38eaa7e70306978a4.

**Comment by nimit2801** [comment]
LGTM! @shreyanshi16
